project:
  type: website
  output-dir: docs

website:
  title: "Entrevista Psiquiátrica e Exame do Estado Mental"
  site-url: "https://henriquealvarenga.com"
  site-path: "/entrevista"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: "Início"
      - href: 01-entrevista_psiquiatrica.qmd
        text: "A Entrevista"
      - href: 02-roteiro_eem.qmd
        text: "Roteiro"
      - href: 03-casos_clinicos.qmd
        text: "Casos"



format:
  html:
    theme: 
      - cosmo
    toc: true
    toc-depth: 3
    number-sections: true
    code-fold: false
    df-print: paged
    css: styles.css

